### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by YuiHrsw** [sam20908/vscode-fastolympiccoding#8]
The extension is pretty good, but I've noticed some feature in sublime is not avaiable in this extension.

- Automatically save modified file before compile and run
- Show AC testcases details
- Use RE/CE for runtime error and compile error

**Comment by sam20908** [comment]
ye sure i can add those 2

**Comment by YuiHrsw** [comment]
> All 3 suggestions are implemented as of commit [396ca5d](https://github.com/sam20908/vscode-fastolympiccoding/commit/396ca5ddaa11b5d1af1d298425859a1eba4fd80c), which will be in version 1.0.2 in a bit

Thank you for your excellent work :)
I've upgraded to the latest version.
It looks like that the auto save feature will make the extension ignore file changes and force compile.
And what about implementing the show/hide button in the AC textblock, just like sublime do?

**Comment by sam20908** [comment]
> It looks like that the auto save feature will make the extension ignore file changes and force compile.

Hmm that's weird, it shouldn't do anything new since I'm just saving the file, I will look.

**Comment by sam20908** [comment]
All fixed as of version 1.0.3, which is released.
